### ISSUE TITLE
Bazarr is broken (1.4.2)

### ISSUE THREAD

**Issue by samip5** [onedr0p/containers#1039]
It seems that after upgrading python to 3.11, the postgres support broke.

Using `ghcr.io/onedr0p/bazarr:1.4.2@sha256:a1d6776fb231803baabe37271783cc38e6b5aebff03ec5a68822c2f81ce8ab81`

```
Defaulted container "main" out of: main, subcleaner
Bazarr starting...
Traceback (most recent call last):
  File "/app/bazarr/main.py", line 22, in <module>
    from init import *  # noqa E402
    ^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/init.py", line 21, in <module>
    from app.database import init_db
  File "/app/bazarr/app/database.py", line 57, in <module>
    engine = create_engine(url, poolclass=NullPool, isolation_level="AUTOCOMMIT")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/app/bazarr/../libs/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/sqlalchemy/engine/create.py", line 600, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/../libs/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: Error loading shared library libpq.so.5: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/psycopg2/_psycopg.cpython-311-x86_64-linux-musl.so)
Bazarr exited.
```

**Comment by samip5** [comment]
Fixed in 80cd69c85fa0d1d69e33e1d50928d935475e92b7
