### ISSUE TITLE
Home Assistant image - ffmpeg dep

### ISSUE THREAD

**Issue by rust84** [onedr0p/containers#43]
Hey, 

Would you be able to add ffmpeg to the image? It seems to be a dependency of ha-ffmpeg. 

```
FFmpeg fails [Errno 2] No such file or directory: 'ffmpeg'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/haffmpeg/core.py", line 136, in open
    self._proc = await self._loop.run_in_executor(None, proc_func)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

**Comment by onedr0p** [comment]
You'll want to use ffmpeg4, I couldn't build the image with ffmpeg 5 which is default on alpine 3.15. But I can try again!

**Comment by onedr0p** [comment]
It built 🎉  I just pushed a commit and a new image should be up soon!

**Comment by rust84** [comment]
Awesome, thanks! All errors are gone now 🙂
