### ISSUE TITLE
Jellyfin big mad

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/containers#8]
```
Unhandled Exception
System.UnauthorizedAccessException: Access to the path '/config/data/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Emby.Server.Implementations.AppBase.BaseApplicationPaths..ctor(String programDataPath, String logDirectoryPath, String configurationDirectoryPath, String cacheDirectoryPath, String webDirectoryPath)
   at Emby.Server.Implementations.ServerApplicationPaths..ctor(String programDataPath, String logDirectoryPath, String configurationDirectoryPath, String cacheDirectoryPath, String webDirectoryPath)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/data/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Emby.Server.Implementations.AppBase.BaseApplicationPaths..ctor(String programDataPath, String logDirectoryPath, String configurationDirectoryPath, String cacheDirectoryPath, String webDirectoryPath)
   at Emby.Server.Implementations.ServerApplicationPaths..ctor(String programDataPath, String logDirectoryPath, String configurationDirectoryPath, String cacheDirectoryPath, String webDirectoryPath)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
```

**Comment by onedr0p** [comment]
Much happy now
