### ISSUE TITLE
Radarr issue

### ISSUE THREAD

**Issue by ilbarone87** [onedr0p/containers#908]
Hello,
seems I'm getting an issue if i try to run Radarr with a different PUID/PGID.
I'm running Radarr in a k8s cluster
```
/entrypoint.sh: line 26: /config/config.xml: Permission denied
[Info] Bootstrap: Starting Radarr - /app/bin/Radarr - Version 5.0.3.8127 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Error] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider: An error occurred while reading the key ring. 

[v5.0.3.8127] System.UnauthorizedAccessException: Access to the path '/config/asp' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.DirectoryInfo.Create()
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)


[Trace] DiskProviderBase: Directory '/config' isn't writable. Access to the path '/config/radarr_write_test.txt' is denied. 
[Fatal] Microsoft.AspNetCore.Hosting.Diagnostics: Application startup exception 

[v5.0.3.8127] NzbDrone.Common.Exceptions.RadarrStartupException: Radarr failed to start: AppFolder /config is not writable
   at NzbDrone.Common.EnvironmentInfo.AppFolderFactory.Register() in ./Radarr.Common/EnvironmentInfo/AppFolderFactory.cs:line 56
   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, IEventAggregator eventAggregator, RadarrErrorPipeline errorHandler) in ./Radarr.Host/Startup.cs:line 226
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)




[Fatal] ConsoleApp: EPIC FAIL! 

[v5.0.3.8127] NzbDrone.Common.Exceptions.RadarrStartupException: Radarr failed to start: AppFolder /config is not writable
   at NzbDrone.Common.EnvironmentInfo.AppFolderFactory.Register() in ./Radarr.Common/EnvironmentInfo/AppFolderFactory.cs:line 56
   at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, IEventAggregator eventAggregator, RadarrErrorPipeline errorHandler) in ./Radarr.Host/Startup.cs:line 226
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in ./Radarr.Host/Bootstrap.cs:line 78
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in ./Radarr.Console/ConsoleApp.cs:line 43


Press enter to exit...
Non-recoverable failure, waiting for user intervention...

```

My deployment yaml file

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr

spec:
  selector:
    matchLabels:
      app: radarr
  serviceName: radarr
  replicas: 1
  template:
    metadata:
      labels:
        app: radarr

    spec:
      securityContext:
          runAsUser: 1030
          runAsGroup: 100
      containers:
      - name: radarr
        #image: ghcr.io/onedr0p/radarr:5.0.3.8127
        imagePullPolicy: Always
        ports:
        - containerPort: 7878
          name: tcp
        volumeMounts:
        - mountPath: /config
          name: radarr


        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1030"
        - name: PGID
          value: "100"    
      
      volumes:
      - name: radarr
        persistentVolumeClaim:
          claimName: radarr
```

**Comment by onedr0p** [comment]
```yaml
securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 100
        runAsUser: 1030
```

Try using this config for the security context

**Comment by onedr0p** [comment]
Also those PGID and PUID env vars don't do anything, you can remove them
